
spring:
  cloud:
    gateway:
      routes:
      - id: EMPLOYEES
        uri: lb://EMPLOYEES
        predicates:
        - Path=/employee/*** 
        
      - id: LEAVEMANAGEMENT
        uri: lb://LEAVEMANAGEMENT
        predicates:
        - Path=/**        
