

server:
  port: 9095
  
spring:
  cloud:
    gateway:
      routes:
      - id: EMPLOYEES
        uri: lb://EMPLOYEES
        predicates:
        - Path=/employees/** 
        
      - id: LEAVEMANAGEMENT
        uri: lb://LEAVEMANAGEMENT
        predicates:
        - Path=/leave/**        

  application:
    name: API-GATEWAY
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka







